#!/usr/bin/env python
# Add NVIDIA libraries to .venv/lib and .venv/lib64
import nvidia
import os
from pathlib import Path


def link_library(path, lib: Path):
    if not lib.is_file():
        return
    if lib.suffix.endswith("py"):
        return

    src = Path(path, lib.name)
    src.unlink(missing_ok=True)
    src.symlink_to(lib.resolve())


def __add_nvidia_libraries():
    for path in Path(nvidia.__path__[0]).iterdir():
        lib = Path(path, "lib")
        if lib.is_dir():
            for file in lib.iterdir():
                link_library(Path(".venv", "lib"), file)
                link_library(Path(".venv", "lib64"), file)


__add_nvidia_libraries()
