mpiexe:
  np: "${NTOTRANKS}"
  ppn: "${NRANKS_PER_NODE}"
  depth: "${NDEPTH}"
  cpu-bind: depth
train:
  model: RoBERTa
  data: RobertaDataSet
  trainer.max_epochs: 5
  trainer.limit_val_batches: 200
  trainer.limit_train_batches: 200
  data.batch_size: 128
  data.tokenizer: ./vendor/MoLFormer-XL-both-10pct/
