#!/usr/bin/env python
import json
import typer
import shutil
from uuid import uuid1
from pathlib import Path

cli = typer.Typer()


@cli.command()
def collate(jobid: str):
    dir = Path(jobid)
    dir.mkdir(parents=True, exist_ok=True)
    for file in Path().glob(f"*{jobid}*"):
        shutil.move(file, dir)

    # Create nsys-report view if needed
    view = {
        "extension": "nsys-view",
        "files": [file.name for file in dir.glob("*.nsys-rep")],
        "uuid": "{{{}}}".format(uuid1()),
        "version": "1.0",
    }
    if view["files"]:
        with open(dir.joinpath(f"{jobid}.nsys-view"), "w") as fid:
            json.dump(view, fid, indent=4)


if __name__ == "__main__":
    cli()
