on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.8
          cache: 'poetry'
      - run: poetry install
      - run: poetry run python -m pip install ./smirk  # Explicitly install smirk to ensure it get's built
      - run: source activate && pytest
