on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.8
          cache: 'poetry'
      - run: poetry install
      - uses: pre-commit/action@v3.0.1
