name: smirk-ci

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./smirk
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: poetry -C ../ run python -m pip install .
      - run: poetry -C ../ run pytest

  python:
    runs-on: ubuntu-latest
    steps:
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10.9
    - run: poetry install --only=dev
    - run: poetry run python -m pip install ./smirk
    - run: poetry run pytest ./smirk
